#!/bin/bash

# 🔍 Check Your Existing Database Connection

echo "╔════════════════════════════════════════════════════╗"
echo "║  📊 EXISTING DATABASE CONNECTION CHECK            ║"
echo "╚════════════════════════════════════════════════════╝"
echo ""

echo "Your .env file currently has a TEMPLATE URL:"
grep "^DATABASE_URL=" .env 2>/dev/null | sed 's/DATABASE_URL=/  → /'
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 To connect your existing PostgreSQL database:"
echo ""
echo "1. Locate your real database connection string"
echo "   It should look like:"
echo "   postgresql://user:password@host.com:5432/dbname"
echo ""
echo "2. Replace the template in .env with your actual URL:"
echo "   $ nano .env"
echo "   (or use any text editor)"
echo ""
echo "3. Save the file and test the connection:"
echo "   $ npx prisma db execute --stdin <<< \"SELECT 1;\""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "❓ Where to find your database URL:"
echo ""
echo "If you're using:"
echo "  • Supabase: Settings → Database → Connection String"
echo "  • Neon: Dashboard → Connection Details"  
echo "  • Railway: Database → Variables → DATABASE_URL"
echo "  • Vercel: Storage → Database → .env.local"
echo "  • Heroku: Settings → Config Vars → DATABASE_URL"
echo "  • Local: postgresql://postgres:yourpassword@localhost:5432/nexus_platform"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 QUICK TEST:"
echo ""
echo "If you have your database URL, test it directly:"
echo ""
echo "  export DATABASE_URL=\"your-real-database-url-here\""
echo "  npx prisma db execute --stdin <<< \"SELECT 1;\""
echo ""
echo "If it says 'Executed successfully' → Add it to .env"
echo "If it fails → Check the URL is correct"
echo ""
